name: flutter_study_workspace
description: Flutter Study workspace container.
publish_to: 'none'

environment:
  sdk: ^3.11.5

workspace:
  - apps/flutter_study
  - packages/gcode_core
  - packages/flutter_study_learning
  - packages/file_picker_bridge
  - packages/flutter_ioc_core
