function writeRoutes({ modules, categoryComments, categoryEnumNames, writeText }) {
  function conceptsLiteral(concepts) {
    const literal = `[${concepts.map((item) => `'${item}'`).join(', ')}]`;
    if (literal.length + 14 <= 80) return literal;
    const items = concepts.map((item) => `      '${item}',`).join('\n');
    return `[\n${items}\n    ]`;
  }

  function writeRouteTable() {
    const lines = [];

    lines.push('// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT');
    lines.push('');
    lines.push("import 'package:go_router/go_router.dart';");
    lines.push('');
        lines.push("import 'module_category.dart';");
    lines.push("import 'module_entry.dart';");
    lines.push("import 'module_platform_policies.dart';");

    for (const m of modules) {
      for (const fileName of ['module_entry.dart', m.routes ? 'module_routes.dart' : null].filter(Boolean)) {
        lines.push(`import '../modules/${m.category}/${m.id}/${fileName}';`);
      }
    }

    lines.push('');
    if (modules.some((m) => m.subRoutesExpander)) {
      lines.push('// ==================== 状态管理子路由（模块内部已定义映射） ====================');
      lines.push('');
      lines.push('List<GoRoute> _buildStatusManageRoutes() => StatusManagementRoutes');
      lines.push('    .routes');
      lines.push('    .entries');
      lines.push('    .map(');
      lines.push('      (entry) => GoRoute(');
      lines.push("        path: entry.key.startsWith('/') ? entry.key.substring(1) : entry.key,");
      lines.push('        builder: (context, state) => entry.value(context),');
      lines.push('      ),');
      lines.push('    )');
      lines.push('    .toList();');
      lines.push('');
    }
    lines.push('// ==================== 模块注册 ====================');
    lines.push('');
    lines.push('final List<ModuleEntry> moduleManifest = [');
    let previousCategory = null;
    for (const m of modules) {
      if (m.category !== previousCategory) {
        if (previousCategory !== null) lines.push('');
        lines.push(`  // ${categoryComments[m.category]}`);
        previousCategory = m.category;
      }
      lines.push('  ModuleEntry(');
      lines.push(`    title: '${m.title}',`);
      lines.push(`    path: '${m.route}',`);
      lines.push(`    subtitle: '${m.subtitle}',`);
      lines.push(`    category: ModuleCategory.${categoryEnumNames[m.category]},`);
      lines.push(`    difficulty: Difficulty.${m.difficulty},`);
      lines.push(`    concepts: ${conceptsLiteral(m.concepts)},`);
      lines.push(`    estimatedMinutes: ${m.estimatedMinutes},`);
      lines.push(`    status: ModuleStatus.${m.status},`);
      lines.push(`    platformSupport: modulePlatformPolicies['${m.id}']!,`);
      lines.push(`    builder: (context) => const ${m.entry}(),`);
      if (m.subRoutesExpander) {
        lines.push('    routes: _buildStatusManageRoutes(),');
      } else if (m.routes) {
        lines.push(`    routes: ${m.routes}.routes,`);
      }
      lines.push('  ),');
    }
    lines.push('];');
    lines.push('');

    writeText('lib/module_registry/module_manifest.dart', lines.join('\n'));

    const routeLines = [];
    routeLines.push('// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT');
    routeLines.push('');
    routeLines.push("import 'package:go_router/go_router.dart';");
    routeLines.push('');
    routeLines.push("import '../adaptive_app_shell.dart';");
    routeLines.push("import '../creator_home_page.dart';");
    routeLines.push("import '../module_home_page.dart';");
    routeLines.push("import '../unsupported_module_page.dart';");
    routeLines.push("import '../../module_registry/app_platform_snapshot.dart';");
    routeLines.push("import '../../module_registry/module_catalog_utils.dart';");
    routeLines.push("import '../../module_registry/module_entry.dart';");
    routeLines.push("import '../../module_registry/module_category.dart';");
    routeLines.push("import '../../module_registry/module_manifest.dart';");
    routeLines.push('');
    routeLines.push('List<GoRoute> _moduleRoutesFor(AppPlatformSnapshot platform) =>');
    routeLines.push('    buildModuleRoutes(');
    routeLines.push('      moduleManifest,');
    routeLines.push('      platform,');
    routeLines.push('      unsupportedBuilder: (_, module) =>');
    routeLines.push('          UnsupportedModulePage(module: module, platform: platform),');
    routeLines.push('    );');
    routeLines.push('');
    routeLines.push('List<RouteBase> _routesFor(AppPlatformSnapshot platform) => [');
    routeLines.push('  ShellRoute(');
    routeLines.push('    builder: (context, state, child) => AdaptiveAppShell(');
    routeLines.push('      modules: moduleManifest,');
    routeLines.push('      location: state.uri.path,');
    routeLines.push('      child: child,');
    routeLines.push('    ),');
    routeLines.push('    routes: [');
    routeLines.push("      GoRoute(path: '/', builder: (context, state) => const CreatorHomePage()),");
    routeLines.push('      GoRoute(');
    routeLines.push("        path: '/category/:category',");
    routeLines.push('        builder: (context, state) {');
    routeLines.push("          final name = state.pathParameters['category'];");
    routeLines.push('          final category = ModuleCategory.values.firstWhere(');
    routeLines.push('            (candidate) => candidate.name == name,');
    routeLines.push('            orElse: () => ModuleCategory.basic,');
    routeLines.push('          );');
    routeLines.push('          return CategoryHomePage(');
    routeLines.push('            category: category,');
    routeLines.push('            modules: moduleManifest,');
    routeLines.push('            platform: platform,');
    routeLines.push('          );');
    routeLines.push('        },');
    routeLines.push('      ),');
    routeLines.push('      ..._moduleRoutesFor(platform),');
    routeLines.push('    ],');
    routeLines.push('  ),');
    routeLines.push('];');
    routeLines.push('');
    routeLines.push('class AppRouteTable {');
    routeLines.push('  static List<RouteBase> routesFor(AppPlatformSnapshot platform) =>');
    routeLines.push('      _routesFor(platform);');
    routeLines.push('  static List<GoRoute> moduleRoutesFor(AppPlatformSnapshot platform) =>');
    routeLines.push('      _moduleRoutesFor(platform);');
    routeLines.push('  static List<ModuleEntry> get modules => moduleManifest;');
    routeLines.push('}');
    routeLines.push('');

    writeText('lib/app/router/app_route_table.dart', routeLines.join('\n'));
  }

  writeRouteTable();
}
module.exports = { writeRoutes };
