const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { targets, dartFiles } = require('./availability');
const { acceptanceCases, casePlatforms } = require('./acceptance_cases');

const evidenceDirectory = 'docs/module_availability/evidence';
const kinds = ['logic', 'compile', 'execution', 'ui'];
const sha256 = (content) => crypto.createHash('sha256').update(content).digest('hex');

function relativeFile(root, rel) {
  if (!rel || path.isAbsolute(rel) || rel.split(/[\\/]/).includes('..')) throw new Error(`Invalid evidence path: ${rel}`);
  const file = path.join(root, rel);
  // Refuse symlinks in parents too: a relative path must not escape the checkout.
  let cursor = root;
  for (const segment of rel.split('/')) {
    cursor = path.join(cursor, segment);
    if (fs.existsSync(cursor) && fs.lstatSync(cursor).isSymbolicLink()) throw new Error(`Evidence must not be a symlink: ${rel}`);
  }
  return file;
}

function sourceFiles(root, directories) {
  const files = [];
  function walk(directory) {
    if (!fs.existsSync(directory)) return;
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (entry.name.startsWith('.') || ['build', 'ephemeral', 'Pods', 'node_modules'].includes(entry.name)) continue;
      const file = path.join(directory, entry.name);
      if (entry.isSymbolicLink()) throw new Error(`Fingerprint source must not be a symlink: ${file}`);
      if (entry.isDirectory()) walk(file);
      else if (file.includes(`${path.sep}assets${path.sep}`) || file.includes('Assets.xcassets') ||
          ['CMakeLists.txt', 'Podfile'].includes(entry.name) || /\.(dart|js|yaml|lock|xml|plist|kt|kts|java|gradle|cpp|cc|c|h|m|mm|swift|html|json|vert|frag|glsl|xcconfig|pbxproj|xcscheme|entitlements|properties|cmake)$/.test(entry.name)) {
        const content = fs.readFileSync(file);
        if (!content.toString('utf8', 0, 150).includes('GENERATED by tool/generate_agent_indexes.js')) files.push(file);
      }
    }
  }
  directories.forEach((rel) => walk(path.join(root, rel)));
  return files;
}

function fingerprint(root, modules, moduleId, kind, platform) {
  const selected = moduleId === '*' ? modules : modules.filter((module) => module.id === moduleId);
  if (!selected.length || (moduleId === '*' && kind !== 'compile')) throw new Error(`Invalid evidence module: ${moduleId}`);
  const global = kind !== 'logic';
  const directories = [
    ...(global ? modules : selected).map((module) => `apps/flutter_forge/lib/modules/${module.category}/${module.id}`),
    ...selected.map((module) => `apps/flutter_forge/test/modules/${module.category}/${module.id}`),
    'apps/flutter_forge/lib/shared', 'apps/flutter_forge/lib/module_registry',
    'packages/file_picker_bridge/lib', 'packages/flutter_ioc_core/lib', 'packages/desktop_multi_window/lib',
    'packages/flutter_battery/lib', 'packages/flutter_battery/test',
    ...(global ? ['apps/flutter_forge/lib/app', 'apps/flutter_forge/integration_test', 'apps/flutter_forge/assets',
      `apps/flutter_forge/${({ macOS: 'macos', iOS: 'ios' })[platform] ?? platform}`,
      ...['file_picker_bridge', 'desktop_multi_window', 'flutter_battery'].flatMap((name) => ['android', 'ios', 'macos', 'windows', 'web'].map((host) => `packages/${name}/${host}`))] : []),
  ];
  const files = [...new Set([...sourceFiles(root, directories),
    ...['pubspec.yaml', 'pubspec.lock', 'apps/flutter_forge/pubspec.yaml', 'apps/flutter_forge/lib/main.dart', 'tool/generate_agent_indexes.js', 'tool/module_availability.js',
      'tool/agent_indexes/availability.js', 'tool/agent_indexes/routes.js', 'tool/agent_indexes/catalog.js', 'tool/agent_indexes/verification.js',
      ...(kind === 'ui' ? ['tool/agent_indexes/acceptance_cases.js', 'tool/agent_indexes/visual_flows.js'] : []),
      'packages/flutter_battery/pubspec.yaml', 'tool/build_web_release.sh', 'packages/file_picker_bridge/pubspec.yaml', 'packages/flutter_ioc_core/pubspec.yaml', 'packages/desktop_multi_window/pubspec.yaml']
      .map((rel) => path.join(root, rel)).filter((file) => fs.existsSync(file))])].sort();
  return sha256(JSON.stringify({ moduleId, kind, platform, policy: selected.map((module) => [module.id, module.excludedPlatforms, module.platformPolicy]),
    files: files.map((file) => [path.relative(root, file), sha256(fs.readFileSync(file))]) }));
}

function testInventory(root, module) {
  const directory = `apps/flutter_forge/test/modules/${module.category}/${module.id}`;
  const files = dartFiles(path.join(root, directory));
  return {
    directory, files: files.map((file) => path.relative(root, file)),
    behaviors: files.flatMap((file) => [...fs.readFileSync(file, 'utf8').matchAll(/\b(testWidgets|test)\s*\(\s*(['"])([^\n]*?)\2/g)]
      .map((match) => ({ name: match[3], kind: match[1] === 'testWidgets' ? 'widget' : 'logic', source: path.relative(root, file) }))),
  };
}

function readEvidence(root, modules) {
  const directory = relativeFile(root, evidenceDirectory);
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory).filter((name) => name.endsWith('.json')).sort().map((name) => {
    const record = JSON.parse(fs.readFileSync(relativeFile(root, `${evidenceDirectory}/${name}`), 'utf8'));
    if (record.schema !== 'flutter_forge.module_evidence.v1' || !kinds.includes(record.kind) ||
        !['pass', 'fail'].includes(record.status) || typeof record.environment !== 'string' || !record.environment.trim() ||
        !/^[a-f0-9]{40}$/.test(record.revision?.commit) || typeof record.revision?.dirty !== 'boolean' ||
        !/^\d{4}-\d{2}-\d{2}T/.test(record.recorded_at) || !Number.isFinite(Date.parse(record.recorded_at)) ||
        !/^[a-f0-9]{64}$/.test(record.fingerprint) || !record.artifacts?.length ||
        (record.platform !== 'any' && !targets.includes(record.platform)) ||
        (record.kind === 'logic' ? record.platform !== 'any' : record.platform === 'any') ||
        (record.kind === 'compile' ? record.module !== '*' : !/^[a-z][a-z0-9_]*$/.test(record.module))) {
      throw new Error(`Invalid module evidence: ${name}`);
    }
    for (const artifact of record.artifacts) {
      const file = relativeFile(root, artifact.path);
      if (!fs.existsSync(file) || !fs.statSync(file).isFile() || sha256(fs.readFileSync(file)) !== artifact.sha256) {
        throw new Error(`Missing or changed evidence artifact: ${artifact.path}`);
      }
    }
    if (['logic', 'compile'].includes(record.kind) || record.source === 'automated_command') {
      if (record.source !== 'automated_command' || !Array.isArray(record.command) || !record.command.length ||
          (record.status === 'pass' && (record.exit_code !== 0 || (record.kind !== 'compile' &&
            (!record.test_summary?.success || record.test_summary.completed <= 0 || record.test_summary.failed !== 0 || record.test_summary.skipped !== 0))))) {
        throw new Error(`Invalid automated verification result: ${name}`);
      }
    } else if (record.source !== 'manual_operator_record') {
      throw new Error(`Unknown verification provenance: ${name}`);
    }
    if (record.kind === 'ui') {
      if (!Array.isArray(record.case_ids) || !record.case_ids.length || new Set(record.case_ids).size !== record.case_ids.length ||
          record.case_ids.some((id) => typeof id !== 'string' || !id)) throw new Error(`Invalid UI case IDs: ${name}`);
      const module = modules.find((item) => item.id === record.module);
      if (module && record.fingerprint === fingerprint(root, modules, record.module, 'ui', record.platform)) {
        const ids = acceptanceCases(module).filter((item) => casePlatforms(module, item, targets).includes(record.platform)).map((item) => item.id);
        if (record.case_ids.some((id) => !ids.includes(id)) || (record.status === 'pass' && ids.some((id) => !record.case_ids.includes(id)))) {
          throw new Error(`UI evidence needs all applicable cases: ${name}`);
        }
      }
    }
    return record;
  });
}

function verificationState(root, modules, records, module, kind, platform, cache = new Map()) {
  const candidates = records.filter((record) => record.kind === kind && record.platform === platform &&
    (record.module === module.id || (kind === 'compile' && record.module === '*')))
    .sort((a, b) => b.recorded_at.localeCompare(a.recorded_at));
  if (!candidates.length) return { status: 'pending' };
  const current = candidates.find((record) => {
    const key = `${record.module}/${kind}/${platform}`;
    if (!cache.has(key)) cache.set(key, fingerprint(root, modules, record.module, kind, platform));
    return record.fingerprint === cache.get(key);
  });
  return { status: current?.status ?? 'stale', evidence: current ?? candidates[0] };
}

function writeAvailability({ root, modules, writeJson, writeText }) {
  const records = readEvidence(root, modules);
  const cache = new Map();
  for (const module of modules) {
    for (const item of acceptanceCases(module)) {
      for (const source of item.sources ?? []) {
        if (!fs.existsSync(relativeFile(root, source))) throw new Error(`Missing acceptance source: ${module.id}/${source}`);
      }
    }
  }
  const matrix = modules.map((module) => ({
    id: module.id, title: module.title, route: module.route, policy: module.platformPolicy,
    tests: testInventory(root, module),
    platforms: Object.fromEntries(targets.map((platform) => [platform, {
      entry_open: !module.excludedPlatforms.includes(platform),
      features: Object.fromEntries(Object.entries(module.platformPolicy.features).map(([id, feature]) => [id, feature.platforms.includes(platform)])),
      verification: Object.fromEntries(kinds.map((kind) => [kind, verificationState(root, modules, records, module, kind, kind === 'logic' ? 'any' : platform, cache)])),
    }])),
    cases: acceptanceCases(module).map((item) => ({ ...item, platforms: casePlatforms(module, item, targets) })),
  }));
  writeJson('docs/module_availability/matrix.json', { schema: 'flutter_forge.module_availability.v1',
    semantics: { entry: 'capability_policy_only', verification: 'labels_only_not_admission', stale: 'source_fingerprint_changed',
      logic: 'host_test_execution_not_target_device_acceptance', compile: 'whole_app_build_not_module_runtime',
      ui: 'listed_cases_only_not_all_visual_behaviors', test_inventory: 'literal_names_only_dynamic_names_may_be_omitted' },
    modules: matrix });
  const labels = { pass: 'PASS', fail: 'FAIL', pending: 'PENDING', stale: 'STALE' };
  const lines = ['# 模块可用性与验证矩阵', '', '<!-- GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT -->', '',
    '入口由能力策略推导，验证结果只做标识。PENDING 表示没有记录，STALE 表示来源已经变化；历史报告不自动转为当前验收。', '',
    '逻辑结果来自当前宿主测试，不证明目标设备行为；编译结果属于完整应用，不证明模块实际执行。界面 PASS 仅覆盖列出的人工用例。', '',
    '| 模块 | 平台 | 入口 | 功能差异 | 逻辑 | 编译 | 执行 | 界面 |', '|---|---|---|---|---|---|---|---|'];
  for (const module of matrix) {
    for (const [platform, row] of Object.entries(module.platforms)) {
      const features = Object.entries(row.features).map(([id, enabled]) => `${id}: ${enabled ? '开放' : '关闭'}`).join('；') || '—';
      lines.push(`| ${module.title} | ${platform} | ${row.entry_open ? '开放' : '关闭'} | ${features} | ${kinds.map((kind) => labels[row.verification[kind].status]).join(' | ')} |`);
    }
  }
  lines.push('', '策略依据、测试来源与完整证据引用见 [matrix.json](matrix.json)，人工操作清单见 [acceptance-cases.md](acceptance-cases.md)。', '');
  writeText('docs/module_availability/matrix.md', lines.join('\n'));
  const cases = ['# 人工界面验收用例', '', '<!-- GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT -->', '',
    '每次记录平台、设备、构建模式、版本、窗口尺寸与操作证据。行为测试是用例依据，不能替代真实界面验收。', '',
    '通用用例覆盖入口、布局与重进；存在平台能力差异的模块附专用流程。下列测试名称仅供补充审阅，未自动转成可执行人工步骤；未列出的业务视觉预期仍需补充。', ''];
  for (const module of matrix) {
    cases.push(`## ${module.title}（${module.id}）`, '', `路径：\`${module.route}\`；逻辑测试：\`flutter test ${module.tests.directory.replace('apps/flutter_forge/', '')}\`（在 apps/flutter_forge 执行）。`, '');
    for (const item of module.cases) {
      cases.push(`### ${item.id}`, '', `平台：${item.platforms.join('、') || '无适用平台'}。`, '', `前置条件：${item.preconditions}`, '',
        `操作：${item.steps}`, '', `预期：${item.expected}`, '', `证据：${item.evidence}`, '',
        ...(item.sources ? [`依据：${item.sources.map((source) => `\`${source}\``).join('、')}`, ''] : []));
    }
    cases.push('行为测试来源（待审阅补充模块专属视觉预期）：', '');
    for (const behavior of module.tests.behaviors) cases.push(`- ${behavior.name.replace(/\|/g, '\\|')}（\`${behavior.source}\`）`);
    if (!module.tests.behaviors.length) cases.push('- 未发现字面量测试名称；补充模块行为测试或审阅动态名称。');
    cases.push('');
  }
  writeText('docs/module_availability/acceptance-cases.md', cases.join('\n'));
}

module.exports = { evidenceDirectory, kinds, sha256, relativeFile, fingerprint, testInventory, readEvidence, verificationState, writeAvailability };
