// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT

import 'package:go_router/go_router.dart';

import '../module_home_page.dart';
import '../../module_registry/module_catalog_utils.dart';
import '../../module_registry/module_entry.dart';
import '../../module_registry/module_manifest.dart';

final List<GoRoute> _routes = [
  GoRoute(
    path: '/',
    builder: (context, state) => ModuleHomePage(modules: moduleManifest),
  ),
  for (final module in availableModules(moduleManifest))
    GoRoute(
      path: module.path,
      builder: (context, state) => module.builder(context),
      routes: module.routes,
    ),
];

class AppRouteTable {
  static List<GoRoute> get routes => _routes;
  static List<ModuleEntry> get modules => moduleManifest;
}
