// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT

import 'package:go_router/go_router.dart';

import '../module_home_page.dart';
import '../unsupported_module_page.dart';
import '../../module_registry/app_platform_snapshot.dart';
import '../../module_registry/module_catalog_utils.dart';
import '../../module_registry/module_entry.dart';
import '../../module_registry/module_manifest.dart';

List<GoRoute> _routesFor(AppPlatformSnapshot platform) => [
  GoRoute(
    path: '/',
    builder: (context, state) => ModuleHomePage(modules: moduleManifest),
  ),
  for (final module in moduleManifest)
    GoRoute(
      path: module.path,
      builder: (context, state) => isModuleAvailable(module, platform)
          ? module.builder(context)
          : UnsupportedModulePage(module: module, platform: platform),
      routes: isModuleAvailable(module, platform) ? module.routes : const [],
    ),
];

class AppRouteTable {
  static List<GoRoute> routesFor(AppPlatformSnapshot platform) =>
      _routesFor(platform);
  static List<ModuleEntry> get modules => moduleManifest;
}
