// GENERATED by tool/generate_agent_indexes.js - DO NOT EDIT

import 'app_platform_snapshot.dart';
import 'module_platform_support.dart';

const modulePlatformPolicies = <String, ModulePlatformSupport>{
  'constraint_layout': ModulePlatformSupport(),
  'tree_state': ModulePlatformSupport(),
  'microtask': ModulePlatformSupport(),
  'debounce_throttle': ModulePlatformSupport(),
  'stream_subscription': ModulePlatformSupport(),
  'isolate_basic': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.web},
  ),
  'isolate_task_manager': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.web},
  ),
  'status_management': ModulePlatformSupport(),
  'flutter_ioc': ModulePlatformSupport(),
  'local_persistence': ModulePlatformSupport(),
  'gcode_visualizer': ModulePlatformSupport(
    excludedPlatforms: {
      AppTargetPlatform.android,
      AppTargetPlatform.iOS,
      AppTargetPlatform.web,
      AppTargetPlatform.windows,
    },
  ),
  'adsorption_line': ModulePlatformSupport(),
  'download_animation': ModulePlatformSupport(),
  'font_picker': ModulePlatformSupport(
    features: {
      'font_file_import': {
        AppTargetPlatform.android,
        AppTargetPlatform.macOS,
        AppTargetPlatform.windows,
      },
      'font_preview': {
        AppTargetPlatform.android,
        AppTargetPlatform.iOS,
        AppTargetPlatform.macOS,
        AppTargetPlatform.windows,
      },
    },
  ),
  'flutter_scene_3d': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.iOS, AppTargetPlatform.web},
    features: {
      'scene_controls': {AppTargetPlatform.macOS, AppTargetPlatform.windows},
    },
  ),
  'popup_widgets': ModulePlatformSupport(),
  'popup_list_interaction': ModulePlatformSupport(),
  'scroll_table': ModulePlatformSupport(),
  'overlay_follow_compare': ModulePlatformSupport(),
  'dio_interceptor': ModulePlatformSupport(),
  'usb_detector': ModulePlatformSupport(
    excludedPlatforms: {
      AppTargetPlatform.android,
      AppTargetPlatform.iOS,
      AppTargetPlatform.macOS,
      AppTargetPlatform.web,
      AppTargetPlatform.windows,
    },
  ),
  'bluetooth_ble': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.iOS, AppTargetPlatform.web},
  ),
  'file_picker': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.iOS},
  ),
  'online_video_player': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.iOS},
  ),
  'webview': ModulePlatformSupport(
    excludedPlatforms: {AppTargetPlatform.iOS, AppTargetPlatform.web},
  ),
};
