const path = require('path');
const { categoryComments, categoryEnumNames, workspacePackages, catalogFor } = require('./agent_indexes/catalog');
const { loadFacts, validateModules, generate } = require('./agent_indexes/generator');
const { writeProjectDocuments } = require('./agent_indexes/project');
const { writeContracts } = require('./agent_indexes/contracts');
const { writeRoutes } = require('./agent_indexes/routes');

const root = path.resolve(__dirname, '..');
const appRoot = path.join(root, 'apps/flutter_forge');
const contracts = {
  no_natural_language: true,
  doc_consumer: 'coding_agent',
  doc_mode: 'machine_contract',
};

// Keep the declaration here for existing validator and module admission consumers.
const modules = [
  {
    category: 'basic',
    id: 'constraint_layout',
    route: '/constraint-layout',
    status: 'ready',
    depends: ['shared_learning', 'module_registry'],
    title: '约束与声明式布局',
    subtitle: '拖动父容器约束，实时观察子组件尺寸与 Row、Column、Wrap 布局变化',
    difficulty: 'beginner',
    concepts: ['BoxConstraints', 'LayoutBuilder', 'SizedBox', 'Row', 'Column', 'Wrap', '声明式 UI'],
    estimatedMinutes: 25,
    entry: 'ConstraintLayoutEntry',
    validation: ['flutter analyze', 'flutter test test/modules/basic/constraint_layout'],
  },
  {
    category: 'basic',
    id: 'tree_state',
    route: '/tree-state',
    status: 'recommended',
    depends: ['shared_learning', 'module_registry', 'go_router'],
    title: '三棵树与生命周期',
    subtitle: '理解 Widget/Element/RenderObject 的关系与重建机制',
    difficulty: 'beginner',
    concepts: ['Widget 树', 'Element 树', 'RenderObject', '生命周期'],
    estimatedMinutes: 30,
    entry: 'TreeStateEntry',
    routes: 'TreeStateRoutes',
  },
  {
    category: 'basic',
    id: 'microtask',
    route: '/microtask',
    status: 'recommended',
    depends: ['shared_learning', 'module_registry', 'go_router'],
    title: '事件循环与微任务',
    subtitle: '掌握 Dart 事件循环中微任务队列与事件队列的执行顺序',
    difficulty: 'beginner',
    concepts: ['Microtask', 'Event Queue', 'async/await', 'Zone'],
    estimatedMinutes: 25,
    entry: 'MicrotaskEntry',
    routes: 'MicrotaskRoutes',
  },
  {
    category: 'basic',
    id: 'debounce_throttle',
    route: '/debounce-throttle',
    status: 'ready',
    depends: ['shared_learning', 'module_registry'],
    title: '防抖与节流',
    subtitle: '对比防抖和节流的执行时序，理解适用场景',
    difficulty: 'beginner',
    concepts: ['Debouncer', 'Throttle', 'Timer'],
    estimatedMinutes: 15,
    entry: 'DebounceThrottleEntry',
  },
  {
    category: 'async',
    id: 'stream_subscription',
    route: '/stream-subscription',
    status: 'recommended',
    depends: ['shared_learning', 'module_registry', 'go_router'],
    title: 'Stream 订阅机制',
    subtitle: '学习单订阅流与广播流的区别及使用场景',
    difficulty: 'intermediate',
    concepts: ['StreamController', '单订阅', '广播流', 'Stream 变换'],
    estimatedMinutes: 30,
    entry: 'StreamSubscriptionEntry',
    routes: 'StreamSubscriptionRoutes',
  },
  {
    category: 'async',
    id: 'isolate_basic',
    route: '/isolate-basic',
    status: 'ready',
    depends: ['shared_learning', 'module_registry', 'go_router'],
    title: 'Isolate 并发对比',
    subtitle: '对比主线程与 Isolate 执行耗时计算对 UI 流畅度的影响',
    difficulty: 'intermediate',
    concepts: ['Isolate', 'SendPort', 'ReceivePort', '性能优化'],
    estimatedMinutes: 20,
    entry: 'IsolateTestEntry',
    routes: 'IsolateTestRoutes',
    excludedPlatforms: ['web'],
    platformSupportComment: '// Safari Web validation showed no usable progress lifecycle for Isolate.spawn.',
  },
  {
    category: 'async',
    id: 'isolate_task_manager',
    route: '/isolate-stream',
    status: 'ready',
    depends: ['shared_learning', 'module_registry'],
    title: '多任务 Isolate 管理器',
    subtitle: '使用 Isolate 并行处理多任务，通过 Stream 实时上报进度',
    difficulty: 'advanced',
    concepts: ['Isolate.spawn', '多任务', '进度上报', '暂停/恢复'],
    estimatedMinutes: 35,
    entry: 'IsolateStreamEntry',
    excludedPlatforms: ['web'],
    platformSupportComment: '// Safari Web validation showed tasks stalled at zero progress.',
  },
  {
    category: 'state',
    id: 'status_management',
    route: '/status-management',
    status: 'recommended',
    depends: ['shared_learning', 'provider', 'flutter_riverpod', 'flutter_bloc', 'module_registry', 'go_router'],
    title: '状态管理演进',
    subtitle: '串联 setState、Provider、Riverpod、Bloc，对比不同方案',
    difficulty: 'intermediate',
    concepts: ['Provider', 'Riverpod', 'Bloc', '状态提升', 'FutureProvider'],
    estimatedMinutes: 45,
    entry: 'StatusManageEntry',
    routes: 'StatusManagementRoutes',
    subRoutesExpander: true,
  },
  {
    category: 'state',
    id: 'flutter_ioc',
    route: '/flutter-ioc',
    status: 'ready',
    depends: ['shared_learning', 'flutter_ioc_core', 'provider', 'module_registry'],
    title: 'Flutter IoC 容器',
    subtitle: '自研 IoC 容器实现，支持单例/瞬态/作用域生命周期',
    difficulty: 'advanced',
    concepts: ['IoC', '依赖注入', '生命周期', '作用域'],
    estimatedMinutes: 30,
    entry: 'FlutterIocEntry',
  },
  {
    category: 'state',
    id: 'local_persistence',
    route: '/local-persistence',
    status: 'ready',
    depends: ['shared_learning', 'shared_preferences', 'module_registry'],
    title: '本地持久化',
    subtitle: '使用 shared_preferences 持久化设置项与计数器，理解异步读取与状态恢复',
    difficulty: 'intermediate',
    concepts: ['shared_preferences', '键值存储', '异步读取', '状态恢复', '测试替身'],
    estimatedMinutes: 25,
    entry: 'LocalPersistenceEntry',
  },
  {
    category: 'ui',
    id: 'gcode_visualizer',
    route: '/gcode-visualizer',
    status: 'ready',
    excludedPlatforms: ['android', 'iOS', 'web', 'windows'],
    platformSupportComment: '// The G-code learning module opens only its macOS entry; device evidence is separate.',
    depends: ['shared_learning', 'gcode_core', 'file_picker_bridge', 'module_registry'],
    title: 'G-code 解析与轨迹动画',
    subtitle: '解析 G-code 指令，绘制刀路轨迹并用动画展示执行过程',
    difficulty: 'advanced',
    concepts: ['G-code', 'Parser', 'CustomPaint', 'PathMetric', '动画控制'],
    estimatedMinutes: 45,
    entry: 'GcodeVisualizerEntry',
  },
  {
    category: 'ui',
    id: 'adsorption_line',
    route: '/adsorption-line',
    status: 'ready',
    depends: ['shared_learning', 'provider', 'module_registry'],
    title: '智能吸附线画板',
    subtitle: '类似设计工具的对齐吸附功能，学习自定义绘制与手势',
    difficulty: 'advanced',
    concepts: ['CustomPaint', '手势检测', '吸附算法', '状态管理'],
    estimatedMinutes: 40,
    entry: 'AdsorptionLineEntry',
  },
  {
    category: 'ui',
    id: 'download_animation',
    route: '/download-animation',
    status: 'ready',
    depends: ['shared_learning', 'module_registry', 'go_router'],
    title: '下载飞入动效',
    subtitle: '三种实现方式对比：Custom View / CustomPaint / Overlay',
    difficulty: 'intermediate',
    concepts: ['Tween 动画', 'CustomPaint', 'OverlayEntry', '动画配置'],
    estimatedMinutes: 30,
    entry: 'DownloadAnimationEntry',
    routes: 'DownloadAnimationRoutes',
  },
  {
    category: 'ui',
    id: 'font_picker',
    route: '/font-picker',
    status: 'ready',
    depends: ['shared_learning', 'file_picker_bridge', 'module_registry', 'go_router'],
    title: '字体选择器',
    subtitle: '命名列表中直观对比不同字体族与字重样式，并通过文件选择器加载本地字体',
    difficulty: 'intermediate',
    concepts: ['fontFamily', 'TextStyle', '字重', '字距', '字体 fallback', '平台字体', 'FontLoader', '中台复用'],
    estimatedMinutes: 30,
    entry: 'FontPickerEntry',
    routes: 'FontPickerRoutes',
  },
  {
    category: 'ui',
    id: 'flutter_scene_3d',
    route: '/flutter-scene-3d',
    status: 'ready',
    depends: ['shared_learning', 'flutter_scene', 'vector_math', 'module_registry'],
    title: '教学型 3D 查看器',
    subtitle: '用轨道相机、部件选取与聚焦反馈理解 3D 查看器交互',
    difficulty: 'intermediate',
    concepts: ['轨道相机', 'Scene Raycast', '部件聚焦', 'Reduced Motion'],
    estimatedMinutes: 35,
    entry: 'FlutterScene3dEntry',
    excludedPlatforms: ['iOS', 'web'],
    platformSupportComment: '// Android is view-only; Windows and Android host evidence remains pending.',
  },
  {
    category: 'popup_table',
    id: 'popup_widgets',
    route: '/popup-widgets',
    status: 'ready',
    depends: ['shared_learning', 'shared_popup', 'module_registry'],
    title: '弹窗合集',
    subtitle: '全面展示 Flutter 中的对话框、底部抽屉、菜单等弹窗类型',
    difficulty: 'beginner',
    concepts: ['AlertDialog', 'BottomSheet', 'Overlay', 'ContextMenu'],
    estimatedMinutes: 20,
    entry: 'PopWidgetEntry',
    owns: ['module_entry', 'module_ui', 'module_docs', 'owned_dialog_routes', 'cancellable_popup_chains'],
    validation: ['flutter analyze', 'flutter test test/modules/popup_table/popup_widgets'],
  },
  {
    category: 'popup_table',
    id: 'popup_list_interaction',
    route: '/popup-list-interaction',
    status: 'ready',
    depends: ['shared_learning', 'shared_popup', 'shared_table', 'module_registry', 'go_router'],
    title: '弹窗与列表交互',
    subtitle: 'Flutter 弹窗组件与二维滚动表格的综合演示',
    difficulty: 'beginner',
    concepts: ['Dialog', 'BottomSheet', 'Overlay', 'TableView', '二维滚动'],
    estimatedMinutes: 25,
    entry: 'PopupListInteractionEntry',
    routes: 'PopupListInteractionRoutes',
    owns: ['module_entry', 'module_ui', 'module_docs', 'popup_result_state', 'cell_edit_drafts'],
    validation: ['flutter analyze', 'flutter test test/modules/popup_table/popup_list_interaction'],
  },
  {
    category: 'popup_table',
    id: 'scroll_table',
    route: '/scroll-table',
    status: 'ready',
    depends: ['shared_learning', 'shared_table', 'module_registry'],
    title: '二维滚动表格',
    subtitle: '使用 two_dimensional_scrollables 实现固定表头的表格',
    difficulty: 'beginner',
    concepts: ['TableView', '固定表头', '二维滚动'],
    estimatedMinutes: 15,
    entry: 'ScrollTableEntry',
    owns: ['module_entry', 'module_ui', 'module_docs', 'table_sample_data'],
    validation: ['flutter analyze', 'flutter test test/modules/popup_table/scroll_table'],
  },
  {
    category: 'popup_table',
    id: 'overlay_follow_compare',
    route: '/overlay-compare',
    status: 'ready',
    depends: ['shared_learning', 'module_registry'],
    title: 'Overlay 跟随方案对照组',
    subtitle: '对比 CompositedTransformFollower 与 markNeedsBuild 两种浮层跟随方案',
    difficulty: 'intermediate',
    concepts: ['Overlay', 'LayerLink', 'CompositedTransformFollower', 'markNeedsBuild', 'ScrollController'],
    estimatedMinutes: 30,
    entry: 'OverlayFollowCompareEntry',
  },
  {
    category: 'platform',
    id: 'dio_interceptor',
    route: '/dio-interceptor',
    status: 'ready',
    depends: ['shared_learning', 'dio', 'module_registry', 'go_router'],
    title: 'Dio 拦截器链路',
    subtitle: 'Auth/Error/Retry/Log 拦截器 + 本地 Mock Server 实战',
    difficulty: 'intermediate',
    concepts: ['Dio', '拦截器', 'Token 刷新', 'Mock Server', '重试机制'],
    estimatedMinutes: 35,
    entry: 'InterceptorTestEntry',
    routes: 'InterceptorTestRoutes',
    excludedPlatforms: [],
    platformSupportComment: '// Web uses an in-memory Dio adapter; native hosts keep the localhost mock server.',
  },
  {
    category: 'platform',
    id: 'usb_detector',
    route: '/usb-detector',
    status: 'ready',
    depends: ['shared_learning', 'device_info_plus', 'module_registry'],
    title: 'USB 设备检测',
    subtitle: 'Android USB 设备检测与状态监控',
    difficulty: 'intermediate',
    concepts: ['Android USB', 'MethodChannel', 'Stream 广播', '设备扫描'],
    estimatedMinutes: 25,
    entry: 'UsbDetectorEntry',
    excludedPlatforms: ['android', 'iOS', 'macOS', 'web', 'windows'],
    platformSupportComment: '// Disabled on every target until the module is reframed as a concrete OTG workflow.',
  },
  {
    category: 'platform',
    id: 'bluetooth_ble',
    route: '/bluetooth-ble',
    status: 'ready',
    depends: ['shared_learning', 'universal_ble', 'url_launcher', 'module_registry'],
    owns: ['module_entry', 'module_ui', 'module_docs', 'scan_lifecycle', 'gatt_lifecycle', 'advertisement_history'],
    validation: ['flutter analyze', 'flutter test test/modules/platform/bluetooth_ble'],
    title: 'BLE 连接生命周期',
    subtitle: '观察扫描、连接、服务发现、读取与订阅、断开',
    difficulty: 'intermediate',
    concepts: ['BLE Central', 'GATT', '特征值属性', '通知订阅', '资源释放'],
    estimatedMinutes: 30,
    entry: 'BluetoothBleEntry',
    excludedPlatforms: ['iOS', 'web'],
    platformSupportComment: '// Android, macOS and Windows expose the BLE learning flow; host build and GATT acceptance are tracked separately.',
  },
  {
    category: 'platform',
    id: 'file_picker',
    route: '/file-picker',
    status: 'ready',
    depends: ['shared_learning', 'file_picker_bridge', 'module_registry'],
    title: '文件选择器',
    subtitle: '复用 file_picker_bridge 中台能力，演示扩展过滤、取消分支与平台差异',
    difficulty: 'intermediate',
    concepts: ['FilePickerService', 'MethodChannel', '平台桥接', '扩展名过滤', '取消分支'],
    estimatedMinutes: 20,
    entry: 'FilePickerEntry',
    excludedPlatforms: ['iOS'],
    platformSupportComment: '// Android uses file_selector; Web exposes only the selected filename.',
  },
  {
    category: 'platform',
    id: 'online_video_player',
    route: '/online-video-player',
    status: 'ready',
    depends: ['shared_learning', 'dio', 'video_player', 'video_player_web', 'video_player_win', 'module_registry'],
    title: '在线视频播放',
    subtitle: '使用 video_player 播放在线 HTTP 视频流并操控播放参数',
    difficulty: 'intermediate',
    concepts: ['video_player', '平台播放器', 'HTTP 流', '播放控制', '倍速', 'Controller 生命周期'],
    estimatedMinutes: 35,
    entry: 'OnlineVideoPlayerEntry',
    excludedPlatforms: ['iOS'],
    platformSupportComment: '// Web uses same-origin media; native targets use their registered backends.',
  },
  {
    category: 'platform',
    id: 'webview',
    route: '/webview',
    status: 'ready',
    depends: ['shared_learning', 'module_registry', 'webview_flutter', 'webview_windows'],
    title: '网页容器与跨平台导航',
    subtitle: '学习 Android、macOS、Windows 网页导航与生命周期',
    difficulty: 'intermediate',
    concepts: ['WebView', 'WebView2', '加载进度', '生命周期'],
    estimatedMinutes: 30,
    entry: 'WebViewEntry',
    excludedPlatforms: ['iOS', 'web'],
    platformSupportComment: '// Android/macOS use webview_flutter; Windows uses WebView2.',
  },

];


function run({ check = false } = {}) {
  const facts = loadFacts(root, modules, workspacePackages);
  validateModules(modules, categoryComments, appRoot);
  return generate({ root, appRoot, check }, ({ writeJson, writeText }) => {
    const context = { root, appRoot, modules, contracts, workspacePackages, facts,
      categoryComments, categoryEnumNames, categoryMeta: catalogFor(modules), writeJson, writeText };
    writeProjectDocuments(context);
    writeContracts(context);
    writeRoutes(context);
  });
}

if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== '--check') || args.length > 1) {
    throw new Error('Usage: node tool/generate_agent_indexes.js [--check]');
  }
  const result = run({ check: args.includes('--check') });
  console.log(`agent_indexes:${args.includes('--check') ? 'checked' : 'generated'}:${result.outputs}:changed:${result.changed}`);
}
module.exports = { modules, run };
