name: flutter_ioc_core
description: Pure Dart IoC container core extracted from Flutter study.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
